
package java3.vista;

import java3.controlador.Lista;

public class JFrameMain extends javax.swing.JFrame {

    // Instanciamos un objeto de cada panel.
    PanelAdministrativo ad1 = new PanelAdministrativo();
    PanelAgente ag1 = new PanelAgente();
    PanelMostrDatos pm1 = new PanelMostrDatos();
    PanelAyuda pa1 = new PanelAyuda();
    
    //static Lista list = new Lista ();     // declaro un objeto de tipo Lista, que se cargará con los datos.
    
    Object actual = new Object ();  // para que recoja la lista y la mande al panel de msotrar litado y haga el filtro
        
    public JFrameMain() {      
        initComponents();
        Lista.iniciarAtributos();
    }
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlta = new javax.swing.JMenu();
        eligeAdministrativo = new javax.swing.JMenuItem();
        eligeAgente = new javax.swing.JMenuItem();
        eligeMostrar = new javax.swing.JMenu();
        eligeAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setFont(new java.awt.Font("Verdana Pro Cond", 0, 18)); // NOI18N
        setForeground(new java.awt.Color(153, 153, 153));

        jMenuAlta.setBackground(new java.awt.Color(204, 204, 204));
        jMenuAlta.setText("Altas");

        eligeAdministrativo.setBackground(new java.awt.Color(153, 153, 153));
        eligeAdministrativo.setFont(new java.awt.Font("Verdana Pro Cond", 0, 18)); // NOI18N
        eligeAdministrativo.setText("Administrativo");
        eligeAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eligeAdministrativoActionPerformed(evt);
            }
        });
        jMenuAlta.add(eligeAdministrativo);

        eligeAgente.setFont(new java.awt.Font("Verdana Pro Cond", 0, 18)); // NOI18N
        eligeAgente.setText("Agente");
        eligeAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eligeAgenteActionPerformed(evt);
            }
        });
        jMenuAlta.add(eligeAgente);

        jMenuBar1.add(jMenuAlta);

        eligeMostrar.setText("Listar");
        eligeMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eligeMostrarMouseClicked(evt);
            }
        });
        eligeMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eligeMostrarActionPerformed(evt);
            }
        });
        jMenuBar1.add(eligeMostrar);

        eligeAyuda.setBackground(new java.awt.Color(255, 255, 255));
        eligeAyuda.setText("Ayuda");
        eligeAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eligeAyudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(eligeAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eligeAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eligeAdministrativoActionPerformed
        cambiarContenedor(ad1);
    }//GEN-LAST:event_eligeAdministrativoActionPerformed

    private void eligeAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eligeAgenteActionPerformed
        cambiarContenedor(ag1);
    }//GEN-LAST:event_eligeAgenteActionPerformed

    // Método que no uso finalmente. Si lo comento entero me da fallo en otra clase.
    private void eligeMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eligeMostrarActionPerformed
        
    }//GEN-LAST:event_eligeMostrarActionPerformed

    private void eligeMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eligeMostrarMouseClicked
        cambiarContenedor(pm1);
        actual = Lista.devuelveObjeto();
        pm1.filtrarObjeto(actual);
    }//GEN-LAST:event_eligeMostrarMouseClicked

    private void eligeAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eligeAyudaMouseClicked
       cambiarContenedor(pa1);
    }//GEN-LAST:event_eligeAyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        final JFrameMain app = new JFrameMain();
        
        //recorrerLista();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
        
        }
    
    // Método para comprobar si la lista funciona:
    /*public static void recorrerLista (Lista list){
        //Nodo aux = Nodo.getSiguiente();

        while (list != null)
        {
            System.out.println (" titulo: " + ());
            list = list.getSiguiente();
        }  
    }*/ 
        private void cambiarContenedor(javax.swing.JPanel aux){
            this.setContentPane(aux);
            pack();
        }
    /*@Override
       public String toString()
        {
            return    actual.getNombre() + " \n "
                    + this.getSueldo() + " \n "
                    //+ this.getFechaAlta()) + " \n "               
                    + this.getSueldoMaximo()+ " \n "
                    + this.inmuebles + " \n "
                    + this.incentivoPorVenta;
        }  */
   
    //private final java3.vista.PanelAgente pAltas = new PanelAgente();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem eligeAdministrativo;
    private javax.swing.JMenuItem eligeAgente;
    private javax.swing.JMenu eligeAyuda;
    private javax.swing.JMenu eligeMostrar;
    private javax.swing.JMenu jMenuAlta;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
